ROBOT_NAME: "RobogaitIndoor"
TYPE: "V3"

DATABASE: "server/db_robogait.db"
PATH2DATABASE: "server/server_ddbb.py"
NAME_DATABASE: "database"

PATH2MAP: "server/maps"
START_ROBOT: "ros2 launch roverrobotics_driver mini.launch.py"
NAME_START_ROBOT: "roverrobotics_driver"

MAP_SAVER_CLI: "ros2 run nav2_map_server map_saver_cli -t /map -f "
NAME_MAP_SAVER_CLI: "nav2_map_save"

TF_SERVICE: "ros2 run tf_service tf_service_node"
NAME_TF_SERVICE: "tf_service"

CARTOGRAPHER_LAUNCH: "ros2 launch roverrobotics_driver slam_launch.py"
NAME_CARTOGRAPHER_LAUNCH: "roverrobotics_driver_slam"

NAV2_BRINGUP_LAUNCH: "ros2 launch roverrobotics_driver navigation_nuevo.launch.py map:="
NAME_NAV2_BRINGUP_LAUNCH: "roverrobotics_driver_navigation"

DISTANCE_CONTROLLER: "ros2 run navigation_pkg distance_controller"
NAME_DISTANCE_CONTROLLER: "distance_controller"

DISTANCE_TRACKER: "ros2 run distance_tracker distance2 --ros-args -p box:=false"
NAME_DISTANCE_TRACKER: "distance_tracker"

CAMERA_CONTROLLER : "ros2 run navigation_pkg camera_controller_vel"
NAME_CAMERA_CONTROLLER: "camera_controller"

DYNAMIXEL : "ros2 run navigation_pkg dynamixel_vel"
NAME_DYNAMIXEL: "dynamixel"

PRUEBA: "ros2 run navigation_pkg robot_controller_remapping"
NAME_PRUEBA: "prueba"


TF_TOPIC: "/tf"
CMD_VEL_TOPIC: "/cmd_vel"
INITIAL_POSE_TOPIC: "/initialpose"
GOAL_POSE_TOPIC: "/goal_pose"
WAYPOINT_FOLLOWER_ACTION: "/follow_waypoints"
